files.storage:
  path: C://Users/Mykyta_Trufanov/Desktop/photos/
  default-image: src/main/resources/static/images/no-photo.jpeg
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20971520
      max-request-size: 26214400